### ISSUE TITLE
PEOPLE TAKING YOUR PLUGINS

### ISSUE THREAD

**Issue by XoticRealmsOwnerandDev** [BajanVlogs/ObbyBlaster#2]
i made a exact copy of your plugin CoinFlip bc i still had the phar file i was able to get all the code
https://github.com/XoticRealmsOwnerandDev/CoinFlip

the i posted it on pmmp.io plugins list for people to use and i said it was not created by me (the plugin)

then about 2mins after i posted it this guy made a copy of it and renamed a few things
https://github.com/DarkkzMC/DRKCoinFlip

**Comment by OfficialLilKev** [comment]
Ok thanks for telling me
